
name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Install librsvg and ImageMagick
        run: sudo apt-get update && sudo apt-get install -y librsvg2-bin imagemagick

      - name: Convert SVG banner to JPG
        run: |
          rsvg-convert -h 630 -w 1200 public/banner.svg -o dist/banner.jpg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: brewlyours.com
